### ISSUE TITLE
Install Jars fails

### ISSUE THREAD

**Issue by raskhadafi** [mkristian/jar-dependencies#25]
When I execute JARS_DEBUG=true JARS_VERBOSE=true rake setup as in the example I get:

```
  jar dependencies for pdf_box-1.12.0-java.gemspec . . .
mvn dependency:copy-dependencies dependency:list -DoutputFile=/Users/107446/code/pdf_box/deps.lst -DoutputAbsoluteArtifactFilename=true -DincludeTypes=jar -DoutputScope=true -DuseRepositoryLayout=true -DoutputDirectory=/Users/107446/.m2/repository -f /Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb -Djars.specfile=/Users/107446/code/pdf_box/pdf_box.gemspec -X -s /Users/107446/.m2/settings.xml -Dmaven.repo.local=/Users/107446/.m2/repository
mvn dependency:copy-dependencies dependency:list -DoutputFile=/Users/107446/code/pdf_box/deps.lst -DoutputAbsoluteArtifactFilename=true -DincludeTypes=jar -DoutputScope=true -DuseRepositoryLayout=true -DoutputDirectory=/Users/107446/.m2/repository -f /Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb -Djars.specfile=/Users/107446/code/pdf_box/pdf_box.gemspec -X -s /Users/107446/.m2/settings.xml -Dmaven.repo.local=/Users/107446/.m2/repository
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/107446/.rvm/gems/jruby-9.0.0.0.rc1@pdf_box/gems/ruby-maven-libs-3.3.3/maven-home
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
[DEBUG] Reading global settings from /Users/107446/.rvm/gems/jruby-9.0.0.0.rc1@pdf_box/gems/ruby-maven-libs-3.3.3/maven-home/conf/settings.xml
[DEBUG] Reading user settings from /Users/107446/.m2/settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/107446/.m2/repository
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2 via 172.30.51.8:3130 with username=, password=***
Downloading: https://repo.maven.apache.org/maven2/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom

[DEBUG] Writing tracking file /Users/107446/.m2/repository/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom.lastUpdated
[WARNING] Failed to read extensions descriptor /Users/107446/code/pdf_box/.mvn/extensions.xml: Plugin io.takari.polyglot:polyglot-ruby:0.1.11 or one of its dependencies could not be resolved: Failed to read artifact descriptor for io.takari.polyglot:polyglot-ruby:jar:0.1.11
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /Users/107446/.rvm/gems/jruby-9.0.0.0.rc1@pdf_box/gems/ruby-maven-libs-3.3.3/maven-home/conf/settings.xml
[DEBUG] Reading user settings from /Users/107446/.m2/settings.xml
[DEBUG] Reading global toolchains from /Users/107446/.rvm/gems/jruby-9.0.0.0.rc1@pdf_box/gems/ruby-maven-libs-3.3.3/maven-home/conf/toolchains.xml
[DEBUG] Reading user toolchains from /Users/107446/.m2/toolchains.xml
[DEBUG] Using local repository at /Users/107446/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/107446/.m2/repository
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project  (/Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb) has 1 error
[ERROR]     Non-parseable POM /Users/107446/code/jar-dependencies/lib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
org.apache.maven.model.io.ModelParseException: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1) 
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:130)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:94)
	at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:529)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:269)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1) 
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1557)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1436)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
	at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4354)
	at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:560)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:121)
	... 25 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
rake aborted!
Errno::ENOENT: No such file or directory - /Users/107446/code/pdf_box/deps.lst
/Users/107446/code/jar-dependencies/lib/jars/installer.rb:75:in `load_from_maven'
/Users/107446/code/jar-dependencies/lib/jars/installer.rb:190:in `install_dependencies'
/Users/107446/code/jar-dependencies/lib/jars/installer.rb:180:in `do_install'
/Users/107446/code/jar-dependencies/lib/jars/installer.rb:143:in `install_jars'
/Users/107446/code/jar-dependencies/lib/jars/installer.rb:66:in `install_jars'
/Users/107446/code/pdf_box/lib/tasks/setup.rake:6:in `block in (root)'
/Users/107446/.rvm/gems/jruby-9.0.0.0.rc1@pdf_box/bin/jruby_executable_hooks:15:in `<top>'
Tasks: TOP => setup
(See full trace by running task with --trace)
```

As you see I am running it with jruby-9.0.0.0-rc1 and I have run it with the latest jar-dependencies code.

And the maven version is:

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.074 s
[INFO] Finished at: 2015-06-29T09:51:05+02:00
[INFO] Final Memory: 7M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

**Comment by mkristian** [comment]
from your log
```
Downloading: https://repo.maven.apache.org/maven2/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom

[DEBUG] Writing tracking file /Users/107446/.m2/repository/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom.lastUpdated
[WARNING] Failed to read extensions descriptor /Users/107446/code/pdf_box/.mvn/extensions.xml: Plugin io.takari.polyglot:polyglot-ruby:0.1.11 or one of its dependencies could not be resolved: Failed to read artifact descriptor for io.takari.polyglot:polyglot-ruby:jar:0.1.11
```
could you delete ~/.m2/repository/io/takari/polyglot/polyglot-ruby/0.1.11/ and try it again. probably jar-dependencies would need a force update switch somehow.

**Comment by raskhadafi** [comment]
I tried it with deleting the hole folder ~/.m2/repository but that not helped too.
Do you think it is a local error?

**Comment by raskhadafi** [comment]
I just took a look at ~/.m2/repository/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom.lastUpdated and I think it is a proxy issue.

```
#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Mon Jun 29 10:35:15 CEST 2015
0e457066c91fff7265565a4b26662058120af9dd@172.30.51.8\:3130>@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1435566915078
https\://repo.maven.apache.org/maven2/.error=Could not transfer artifact io.takari.polyglot\:polyglot-ruby\:pom\:0.1.11 from/to central (https\://repo.maven.apache.org/maven2)\: Connect to 172.30.51.8\:3130 [/172.30.51.8] failed\: Connection refused
```

**Comment by mkristian** [comment]
as long there is this error with ```Failed to read extensions descriptor /Users/107446/code/pdf_box/.mvn/extensions.xml``` maven can not use the ruby dsl which jar-dependencies uses. my pom looks OK and we are using verion 0.1.11 for the jruby build.

**Comment by mkristian** [comment]
did you get it to work ?

closing since it looks very much a problem with mirror/proxy used.
