### ISSUE TITLE
Example Walkthrough Fails

### ISSUE THREAD

**Issue by klobuczek** [mkristian/jar-dependencies#68]

**Comment by klobuczek** [comment]
The 3rd step in the example walkthrough fails:
```
heinrich@berlin:~/mck/examples/jar-dependencies/example$ rake --trace
rake aborted!
NameError: cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
org/jruby/ext/jruby/JRubyUtilLibrary.java:184:in `load_ext'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/jopenssl/load.rb:31:in `<main>'
org/jruby/RubyKernel.java:983:in `require'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/openssl.rb:1:in `<main>'
org/jruby/RubyKernel.java:983:in `require'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/openssl.rb:1:in `<main>'
org/jruby/RubyKernel.java:983:in `require'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/security.rb:1:in `<main>'
org/jruby/RubyKernel.java:983:in `require'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/security.rb:12:in `<main>'
org/jruby/RubyKernel.java:983:in `require'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/package.rb:1:in `<main>'
org/jruby/RubyKernel.java:1007:in `load'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/package.rb:44:in `<main>'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/package_task.rb:1:in `(root)'
/Users/heinrich/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/package_task.rb:24:in `block in <main>'
/Users/heinrich/mck/examples/jar-dependencies/example/Rakefile:1:in `(root)'
/Users/heinrich/mck/examples/jar-dependencies/example/Rakefile:26:in `<main>'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/gems/rake-10.5.0/lib/rake/rake_module.rb:1:in `block in (root)'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `<main>'
org/jruby/RubyKernel.java:1007:in `load'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
org/jruby/RubyKernel.java:1046:in `eval'
/Users/heinrich/.rvm/gems/jruby-9.2.5.0/bin/jruby_executable_hooks:24:in `<main>'
```

**Comment by chadlwilson** [comment]
Will re-open if still an issue on modern JRuby.
